services:
  backend-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-api
    restart: always
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:5001/api/v1
    container_name: frontend-app
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - backend-api
