import { PrismaClient, UserStatus } from '@prisma/client';

const prisma = new PrismaClient();

const mockUsers = [
  {
    name: 'Yash Sharma',
    email: 'yash.sharma@example.com',
    primaryMobile: '9876543210',
    secondaryMobile: '9123456780',
    aadhaar: '123456789012',
    pan: 'ABCDE1234F',
    dateOfBirth: new Date('1995-08-15'),
    placeOfBirth: 'Delhi',
    currentAddress: '123 Tech Park, Sector 62, Noida, UP, 201301',
    permanentAddress: '456 Residency Green, Civil Lines, Jaipur, Rajasthan, 302001',
    createdBy: 'SYSTEM_SEED',
    status: UserStatus.ACTIVE,
    remarks: 'Initial administrator user generated by seeding script.',
  },
  {
    name: 'Aanya Patel',
    email: 'aanya.patel@example.com',
    primaryMobile: '9812345678',
    secondaryMobile: null,
    aadhaar: '234567890123',
    pan: 'FGHJI5678K',
    dateOfBirth: new Date('1992-04-20'),
    placeOfBirth: 'Ahmedabad',
    currentAddress: '789 Naranpura, Ahmedabad, Gujarat, 380013',
    permanentAddress: '789 Naranpura, Ahmedabad, Gujarat, 380013',
    createdBy: 'SYSTEM_SEED',
    status: UserStatus.ACTIVE,
    remarks: 'Senior developer user.',
  },
  {
    name: 'Kabir Mehta',
    email: 'kabir.mehta@example.com',
    primaryMobile: '9000123456',
    secondaryMobile: '9876000000',
    aadhaar: '345678901234',
    pan: 'LMNOP9012Q',
    dateOfBirth: new Date('1988-12-10'),
    placeOfBirth: 'Mumbai',
    currentAddress: 'Flat 402, Sea View Apartments, Bandra West, Mumbai, 400050',
    permanentAddress: 'Flat 402, Sea View Apartments, Bandra West, Mumbai, 400050',
    createdBy: 'SYSTEM_SEED',
    status: UserStatus.INACTIVE,
    remarks: 'Deactivated account due to inactivity.',
  },
  {
    name: 'Mira Nair',
    email: 'mira.nair@example.com',
    primaryMobile: '8123456789',
    secondaryMobile: null,
    aadhaar: '456789012345',
    pan: 'RSTUV3456W',
    dateOfBirth: new Date('1997-02-28'),
    placeOfBirth: 'Kochi',
    currentAddress: 'Annex Road, Edappally, Kochi, Kerala, 682024',
    permanentAddress: 'Annex Road, Edappally, Kochi, Kerala, 682024',
    createdBy: 'SYSTEM_SEED',
    status: UserStatus.ACTIVE,
    remarks: 'Marketing associate.',
  },
  {
    name: 'Rohan Gupta',
    email: 'rohan.gupta@example.com',
    primaryMobile: '7890123456',
    secondaryMobile: '7123456789',
    aadhaar: '567890123456',
    pan: 'XYZAB7890C',
    dateOfBirth: new Date('1990-10-05'),
    placeOfBirth: 'Kolkata',
    currentAddress: 'Salt Lake City, Block C, Kolkata, West Bengal, 700091',
    permanentAddress: 'Gupta Niwas, Mall Road, Shimla, Himachal Pradesh, 171001',
    createdBy: 'SYSTEM_SEED',
    status: UserStatus.ACTIVE,
    remarks: 'Relocated to Kolkata, permanent address in Shimla.',
  },
];

async function main() {
  loggerInfo('Starting database seeding...');
  
  // Clear existing users only if empty or to reset, let's keep database checks safe.
  const count = await prisma.user.count();
  if (count === 0) {
    for (const user of mockUsers) {
      await prisma.user.create({
        data: user,
      });
      loggerInfo(`Created user: ${user.name}`);
    }
    loggerInfo('Database seeding completed successfully.');
  } else {
    loggerInfo('Database already has users. Skipping seeding.');
  }
}

function loggerInfo(msg: string) {
  console.log(`[SEED] ${msg}`);
}

main()
  .catch((e) => {
    console.error('Error seeding database:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
